version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: log-symbols
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: youtube-dl
    versions:
    - 3.1.0
    - 3.4.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: chalk
    versions:
    - 4.1.0
